#!/usr/bin/env bash
# Setup script for Next.js + Supabase starter app.
# Assumptions: Supabase is already initialized (supabase/ with migrations and schemas exists).
# Idempotent: safe to run multiple times.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "==> Next.js + Supabase setup"
echo ""

# 1. Check supabase directory exists
if [[ ! -d "supabase" ]]; then
  echo "Error: supabase/ directory not found. Run 'npx supabase init' first."
  exit 1
fi

if [[ ! -d "supabase/migrations" ]]; then
  echo "Error: supabase/migrations/ not found. Ensure Supabase is initialized with migrations."
  exit 1
fi

# 2. npm install
echo "==> Installing dependencies (npm install)..."
npm install
echo ""

# 3. Start Supabase (or use existing)
echo "==> Starting Supabase (npx supabase start)..."
if ! npx supabase start 2>/dev/null; then
  # May already be running; try status to get credentials
  if ! npx supabase status -o env >/dev/null 2>&1; then
    echo "Error: Failed to start Supabase. Is Docker running? See https://supabase.com/docs/guides/cli/local-development"
    exit 1
  fi
  echo "Supabase is already running."
fi
echo ""

# 4. Extract credentials and write .env.local
echo "==> Writing .env.local..."
STATUS=$(npx supabase status -o env 2>/dev/null) || true
if [[ -z "$STATUS" ]]; then
  echo "Error: Could not get Supabase status. Run 'npx supabase start' manually and retry."
  exit 1
fi

API_URL=$(echo "$STATUS" | grep '^API_URL=' | cut -d= -f2- | tr -d '"' | tr -d "'")
ANON_KEY=$(echo "$STATUS" | grep '^ANON_KEY=' | cut -d= -f2- | tr -d '"' | tr -d "'")

if [[ -z "$API_URL" || -z "$ANON_KEY" ]]; then
  echo "Error: Could not parse API_URL or ANON_KEY from 'supabase status'. Check Supabase CLI output."
  exit 1
fi

cat > .env.local << EOF
# Auto-generated by setup.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EOF
echo "Created/updated .env.local with Supabase URL and anon key."
echo ""

# 5. Run migrations
echo "==> Running database migrations (npx supabase db reset)..."
npx supabase db reset
echo ""

echo "==> Setup complete."
echo ""
echo "Next steps:"
echo "  1. Run the app:  npm run dev"
echo "  2. Open http://localhost:3000 in your browser"
echo "  3. Sign up or log in to try the starter app"
echo ""
